command_key = ":"
initial_screen = "library"
use_nerdfont = false
flip_status_indicators = false
backend = "pulseaudio"
# backend_device =    # "ncspot -h" to get available backend devices
audio_cache = true
# audio_cache_size =
volnorm = false
volnorm_pregain = 0.0
default_keybindings = false
notify = false
bitrate = 160
gapless = true
shuffle = false
repeat = "off"
playback_state = "Paused"
library_tabs = ["tracks", "albums", "artists", "playlists", "podcasts", "browse"]
cover_max_scale = 1.0
hide_display_names = false
statusbar_format = "%artists - %tracks"
# ap_port =

[track_format]
# See https://github.com/hrkfdn/ncspot/blob/main/doc/users.md#track-formatting

[notification_format]
# See https://github.com/hrkfdn/ncspot/blob/main/doc/users.md#notification-formatting

[theme]
# See https://github.com/hrkfdn/ncspot/blob/main/doc/users.md#theming

[keybindings]
# See https://github.com/hrkfdn/ncspot/blob/main/doc/users.md#custom-keybindings
